/**
 * ============================================================================
 * SIH26050 ANTI-DRONE 2-AXIS GIMBAL CONTROLLER - STM32 MAIN APPLICATION
 * ============================================================================
 * This application is 100% compatible with:
 *   1. Hardware-In-The-Loop (HIL) Three.js Simulation via bridge.py
 *   2. Physical Camera & Computer Vision (OpenCV/YOLO) Tracking Setup
 *
 * Microcontroller Architecture:
 *   - UART1 / USB VCP @ 115200 Baud (DMA or RXNE Interrupt)
 *   - TIM2 @ 10 kHz (High-Speed Stepper Pulse Generation)
 *   - Systick @ 1 kHz (Kinematics & 20 Hz Telemetry Scheduling)
 * ============================================================================
 */

#include "gimbal_config.h"
#include "stepper_controller.h"
#include "protocol_parser.h"
#include <string.h>

// Forward declarations of STM32 HAL peripheral handles (Generated by CubeMX)
// In your CubeMX project, these are defined in main.c:
// UART_HandleTypeDef huart1;
// TIM_HandleTypeDef htim2;

// Telemetry output buffer
static char tx_telemetry_buf[TX_BUFFER_SIZE];
static uint32_t last_telemetry_tick = 0;
static uint32_t last_kinematics_tick = 0;

/**
 * Custom UART transmit stub (replace with HAL_UART_Transmit in your project)
 */
void Hardware_UART_Transmit(const char* data, uint16_t length) {
#ifdef USE_STM32_HAL
    extern UART_HandleTypeDef huart1;
    HAL_UART_Transmit(&huart1, (uint8_t*)data, length, 50);
#else
    (void)data; (void)length;
#endif
}

/**
 * Call this function from your UART RX Interrupt (USART1_IRQHandler or HAL_UART_RxCpltCallback)
 * whenever a new byte arrives over USB Serial!
 */
void Hardware_UART_OnByteReceived(char byte) {
    if (Protocol_ProcessChar(byte)) {
        // Full newline-delimited command ready!
        const char* rx_line = Protocol_GetRxLine();
        ParsedCommand_t cmd;

        if (Protocol_ParseCommand(rx_line, &cmd)) {
            switch (cmd.type) {
                case CMD_TYPE_RATE_PAN:
                    Stepper_SetRatePan(cmd.axis_dir, cmd.rate_speed);
                    break;

                case CMD_TYPE_RATE_TILT:
                    Stepper_SetRateTilt(cmd.axis_dir, cmd.rate_speed);
                    break;

                case CMD_TYPE_MOVE:
                    Stepper_SetTargetPositions(cmd.pan_target, cmd.tilt_target);
                    break;

                case CMD_TYPE_STOP:
                    Stepper_EmergencyStop();
                    break;

                case CMD_TYPE_HOME:
                    Stepper_HomeAxes();
                    break;

                case CMD_TYPE_ENABLE:
                    Stepper_EnableDrivers(cmd.enable_value);
                    break;

                case CMD_TYPE_STATUS: {
                    char status_buf[64];
                    uint16_t len = Protocol_FormatStatus(status_buf, sizeof(status_buf), 1);
                    Hardware_UART_Transmit(status_buf, len);
                    break;
                }

                default:
                    break;
            }
        }
    }
}

/**
 * Call this function from your high-frequency timer (TIM2 at 10 kHz - 20 kHz)
 */
void Hardware_Timer_OnPeriodElapsed(void) {
    Stepper_TimerInterrupt_Handler();
}

/**
 * Main Firmware Initialization & Execution Loop
 */
int main_gimbal_app(void) {
    // 1. Initialize Subsystems
    Stepper_Init();
    Protocol_Init();

    // 2. Broadcast Startup Status Packet
    char startup_buf[64];
    uint16_t s_len = Protocol_FormatStatus(startup_buf, sizeof(startup_buf), 1);
    Hardware_UART_Transmit(startup_buf, s_len);

    // 3. Superloop (Kinematics & 20 Hz Telemetry Broadcast)
    while (1) {
        uint32_t current_tick = 0; // Replace with HAL_GetTick()

#ifdef USE_STM32_HAL
        extern uint32_t HAL_GetTick(void);
        current_tick = HAL_GetTick();
#endif

        // Periodic Kinematics & Thermal Update (Every 20 ms)
        if (current_tick - last_kinematics_tick >= 20) {
            float dt = (float)(current_tick - last_kinematics_tick) / 1000.0f;
            last_kinematics_tick = current_tick;
            Stepper_UpdateKinematics(dt);
        }

        // Periodic Telemetry Streaming @ 20 Hz (Every 50 ms)
        if (current_tick - last_telemetry_tick >= TELEMETRY_INTERVAL_MS) {
            last_telemetry_tick = current_tick;

            uint16_t len = Protocol_FormatTelemetry(tx_telemetry_buf, sizeof(tx_telemetry_buf));
            if (len > 0) {
                Hardware_UART_Transmit(tx_telemetry_buf, len);
            }
        }
    }

    return 0;
}
